//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("BD_EraCuscoModel", "FK__Adopcion__adopta__1A14E395", "UsuarioAdoptante", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EraCuscoWeb.UsuarioAdoptante), "Adopcion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EraCuscoWeb.Adopcion), true)]
[assembly: EdmRelationshipAttribute("BD_EraCuscoModel", "FK__Adopcion__mascot__182C9B23", "Mascota", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EraCuscoWeb.Mascota), "Adopcion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EraCuscoWeb.Adopcion), true)]
[assembly: EdmRelationshipAttribute("BD_EraCuscoModel", "FK__Adopcion__solici__1B0907CE", "Solicitud", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EraCuscoWeb.Solicitud), "Adopcion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EraCuscoWeb.Adopcion), true)]
[assembly: EdmRelationshipAttribute("BD_EraCuscoModel", "FK__Adopcion__usuari__1920BF5C", "UsuarioAlbergue", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EraCuscoWeb.UsuarioAlbergue), "Adopcion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EraCuscoWeb.Adopcion), true)]
[assembly: EdmRelationshipAttribute("BD_EraCuscoModel", "FK__Mascota__usuario__1DE57479", "UsuarioAlbergue", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EraCuscoWeb.UsuarioAlbergue), "Mascota", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EraCuscoWeb.Mascota), true)]
[assembly: EdmRelationshipAttribute("BD_EraCuscoModel", "FK__Solicitud__masco__1BFD2C07", "Mascota", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EraCuscoWeb.Mascota), "Solicitud", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EraCuscoWeb.Solicitud), true)]
[assembly: EdmRelationshipAttribute("BD_EraCuscoModel", "FK__Solicitud__adopt__1CF15040", "UsuarioAdoptante", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EraCuscoWeb.UsuarioAdoptante), "Solicitud", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EraCuscoWeb.Solicitud), true)]

#endregion

namespace EraCuscoWeb
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class BD_EraCuscoEntidades : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto BD_EraCuscoEntidades usando la cadena de conexión encontrada en la sección 'BD_EraCuscoEntidades' del archivo de configuración de la aplicación.
        /// </summary>
        public BD_EraCuscoEntidades() : base("name=BD_EraCuscoEntidades", "BD_EraCuscoEntidades")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BD_EraCuscoEntidades.
        /// </summary>
        public BD_EraCuscoEntidades(string connectionString) : base(connectionString, "BD_EraCuscoEntidades")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BD_EraCuscoEntidades.
        /// </summary>
        public BD_EraCuscoEntidades(EntityConnection connection) : base(connection, "BD_EraCuscoEntidades")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Adopcion> Adopcion
        {
            get
            {
                if ((_Adopcion == null))
                {
                    _Adopcion = base.CreateObjectSet<Adopcion>("Adopcion");
                }
                return _Adopcion;
            }
        }
        private ObjectSet<Adopcion> _Adopcion;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Mascota> Mascota
        {
            get
            {
                if ((_Mascota == null))
                {
                    _Mascota = base.CreateObjectSet<Mascota>("Mascota");
                }
                return _Mascota;
            }
        }
        private ObjectSet<Mascota> _Mascota;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Solicitud> Solicitud
        {
            get
            {
                if ((_Solicitud == null))
                {
                    _Solicitud = base.CreateObjectSet<Solicitud>("Solicitud");
                }
                return _Solicitud;
            }
        }
        private ObjectSet<Solicitud> _Solicitud;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<UsuarioAdoptante> UsuarioAdoptante
        {
            get
            {
                if ((_UsuarioAdoptante == null))
                {
                    _UsuarioAdoptante = base.CreateObjectSet<UsuarioAdoptante>("UsuarioAdoptante");
                }
                return _UsuarioAdoptante;
            }
        }
        private ObjectSet<UsuarioAdoptante> _UsuarioAdoptante;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<UsuarioAlbergue> UsuarioAlbergue
        {
            get
            {
                if ((_UsuarioAlbergue == null))
                {
                    _UsuarioAlbergue = base.CreateObjectSet<UsuarioAlbergue>("UsuarioAlbergue");
                }
                return _UsuarioAlbergue;
            }
        }
        private ObjectSet<UsuarioAlbergue> _UsuarioAlbergue;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Adopcion. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAdopcion(Adopcion adopcion)
        {
            base.AddObject("Adopcion", adopcion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Mascota. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMascota(Mascota mascota)
        {
            base.AddObject("Mascota", mascota);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Solicitud. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToSolicitud(Solicitud solicitud)
        {
            base.AddObject("Solicitud", solicitud);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet UsuarioAdoptante. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsuarioAdoptante(UsuarioAdoptante usuarioAdoptante)
        {
            base.AddObject("UsuarioAdoptante", usuarioAdoptante);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet UsuarioAlbergue. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsuarioAlbergue(UsuarioAlbergue usuarioAlbergue)
        {
            base.AddObject("UsuarioAlbergue", usuarioAlbergue);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_EraCuscoModel", Name="Adopcion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Adopcion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Adopcion.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static Adopcion CreateAdopcion(global::System.Int32 id)
        {
            Adopcion adopcion = new Adopcion();
            adopcion.id = id;
            return adopcion;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adNombre
        {
            get
            {
                return _adNombre;
            }
            set
            {
                OnadNombreChanging(value);
                ReportPropertyChanging("adNombre");
                _adNombre = StructuralObject.SetValidValue(value, true, "adNombre");
                ReportPropertyChanged("adNombre");
                OnadNombreChanged();
            }
        }
        private global::System.String _adNombre;
        partial void OnadNombreChanging(global::System.String value);
        partial void OnadNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adPaterno
        {
            get
            {
                return _adPaterno;
            }
            set
            {
                OnadPaternoChanging(value);
                ReportPropertyChanging("adPaterno");
                _adPaterno = StructuralObject.SetValidValue(value, true, "adPaterno");
                ReportPropertyChanged("adPaterno");
                OnadPaternoChanged();
            }
        }
        private global::System.String _adPaterno;
        partial void OnadPaternoChanging(global::System.String value);
        partial void OnadPaternoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adMaterno
        {
            get
            {
                return _adMaterno;
            }
            set
            {
                OnadMaternoChanging(value);
                ReportPropertyChanging("adMaterno");
                _adMaterno = StructuralObject.SetValidValue(value, true, "adMaterno");
                ReportPropertyChanged("adMaterno");
                OnadMaternoChanged();
            }
        }
        private global::System.String _adMaterno;
        partial void OnadMaternoChanging(global::System.String value);
        partial void OnadMaternoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adDni
        {
            get
            {
                return _adDni;
            }
            set
            {
                OnadDniChanging(value);
                ReportPropertyChanging("adDni");
                _adDni = StructuralObject.SetValidValue(value, true, "adDni");
                ReportPropertyChanged("adDni");
                OnadDniChanged();
            }
        }
        private global::System.String _adDni;
        partial void OnadDniChanging(global::System.String value);
        partial void OnadDniChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adDireccion
        {
            get
            {
                return _adDireccion;
            }
            set
            {
                OnadDireccionChanging(value);
                ReportPropertyChanging("adDireccion");
                _adDireccion = StructuralObject.SetValidValue(value, true, "adDireccion");
                ReportPropertyChanged("adDireccion");
                OnadDireccionChanged();
            }
        }
        private global::System.String _adDireccion;
        partial void OnadDireccionChanging(global::System.String value);
        partial void OnadDireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tipoVivienda
        {
            get
            {
                return _tipoVivienda;
            }
            set
            {
                OntipoViviendaChanging(value);
                ReportPropertyChanging("tipoVivienda");
                _tipoVivienda = StructuralObject.SetValidValue(value, true, "tipoVivienda");
                ReportPropertyChanged("tipoVivienda");
                OntipoViviendaChanged();
            }
        }
        private global::System.String _tipoVivienda;
        partial void OntipoViviendaChanging(global::System.String value);
        partial void OntipoViviendaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> otrasMascotas
        {
            get
            {
                return _otrasMascotas;
            }
            set
            {
                OnotrasMascotasChanging(value);
                ReportPropertyChanging("otrasMascotas");
                _otrasMascotas = StructuralObject.SetValidValue(value, "otrasMascotas");
                ReportPropertyChanged("otrasMascotas");
                OnotrasMascotasChanged();
            }
        }
        private Nullable<global::System.Int32> _otrasMascotas;
        partial void OnotrasMascotasChanging(Nullable<global::System.Int32> value);
        partial void OnotrasMascotasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> esteriziacion
        {
            get
            {
                return _esteriziacion;
            }
            set
            {
                OnesteriziacionChanging(value);
                ReportPropertyChanging("esteriziacion");
                _esteriziacion = StructuralObject.SetValidValue(value, "esteriziacion");
                ReportPropertyChanged("esteriziacion");
                OnesteriziacionChanged();
            }
        }
        private Nullable<global::System.Int32> _esteriziacion;
        partial void OnesteriziacionChanging(Nullable<global::System.Int32> value);
        partial void OnesteriziacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechaEmision
        {
            get
            {
                return _fechaEmision;
            }
            set
            {
                OnfechaEmisionChanging(value);
                ReportPropertyChanging("fechaEmision");
                _fechaEmision = StructuralObject.SetValidValue(value, "fechaEmision");
                ReportPropertyChanged("fechaEmision");
                OnfechaEmisionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechaEmision;
        partial void OnfechaEmisionChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaEmisionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> mascota
        {
            get
            {
                return _mascota;
            }
            set
            {
                OnmascotaChanging(value);
                ReportPropertyChanging("mascota");
                _mascota = StructuralObject.SetValidValue(value, "mascota");
                ReportPropertyChanged("mascota");
                OnmascotaChanged();
            }
        }
        private Nullable<global::System.Int32> _mascota;
        partial void OnmascotaChanging(Nullable<global::System.Int32> value);
        partial void OnmascotaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> usuarioAlbergue
        {
            get
            {
                return _usuarioAlbergue;
            }
            set
            {
                OnusuarioAlbergueChanging(value);
                ReportPropertyChanging("usuarioAlbergue");
                _usuarioAlbergue = StructuralObject.SetValidValue(value, "usuarioAlbergue");
                ReportPropertyChanged("usuarioAlbergue");
                OnusuarioAlbergueChanged();
            }
        }
        private Nullable<global::System.Int32> _usuarioAlbergue;
        partial void OnusuarioAlbergueChanging(Nullable<global::System.Int32> value);
        partial void OnusuarioAlbergueChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> adoptante
        {
            get
            {
                return _adoptante;
            }
            set
            {
                OnadoptanteChanging(value);
                ReportPropertyChanging("adoptante");
                _adoptante = StructuralObject.SetValidValue(value, "adoptante");
                ReportPropertyChanged("adoptante");
                OnadoptanteChanged();
            }
        }
        private Nullable<global::System.Int32> _adoptante;
        partial void OnadoptanteChanging(Nullable<global::System.Int32> value);
        partial void OnadoptanteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> solicitud
        {
            get
            {
                return _solicitud;
            }
            set
            {
                OnsolicitudChanging(value);
                ReportPropertyChanging("solicitud");
                _solicitud = StructuralObject.SetValidValue(value, "solicitud");
                ReportPropertyChanged("solicitud");
                OnsolicitudChanged();
            }
        }
        private Nullable<global::System.Int32> _solicitud;
        partial void OnsolicitudChanging(Nullable<global::System.Int32> value);
        partial void OnsolicitudChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_EraCuscoModel", "FK__Adopcion__adopta__1A14E395", "UsuarioAdoptante")]
        public UsuarioAdoptante UsuarioAdoptante
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioAdoptante>("BD_EraCuscoModel.FK__Adopcion__adopta__1A14E395", "UsuarioAdoptante").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioAdoptante>("BD_EraCuscoModel.FK__Adopcion__adopta__1A14E395", "UsuarioAdoptante").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UsuarioAdoptante> UsuarioAdoptanteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioAdoptante>("BD_EraCuscoModel.FK__Adopcion__adopta__1A14E395", "UsuarioAdoptante");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UsuarioAdoptante>("BD_EraCuscoModel.FK__Adopcion__adopta__1A14E395", "UsuarioAdoptante", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_EraCuscoModel", "FK__Adopcion__mascot__182C9B23", "Mascota")]
        public Mascota Mascota1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mascota>("BD_EraCuscoModel.FK__Adopcion__mascot__182C9B23", "Mascota").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mascota>("BD_EraCuscoModel.FK__Adopcion__mascot__182C9B23", "Mascota").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Mascota> Mascota1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mascota>("BD_EraCuscoModel.FK__Adopcion__mascot__182C9B23", "Mascota");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Mascota>("BD_EraCuscoModel.FK__Adopcion__mascot__182C9B23", "Mascota", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_EraCuscoModel", "FK__Adopcion__solici__1B0907CE", "Solicitud")]
        public Solicitud Solicitud1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Solicitud>("BD_EraCuscoModel.FK__Adopcion__solici__1B0907CE", "Solicitud").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Solicitud>("BD_EraCuscoModel.FK__Adopcion__solici__1B0907CE", "Solicitud").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Solicitud> Solicitud1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Solicitud>("BD_EraCuscoModel.FK__Adopcion__solici__1B0907CE", "Solicitud");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Solicitud>("BD_EraCuscoModel.FK__Adopcion__solici__1B0907CE", "Solicitud", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_EraCuscoModel", "FK__Adopcion__usuari__1920BF5C", "UsuarioAlbergue")]
        public UsuarioAlbergue UsuarioAlbergue1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioAlbergue>("BD_EraCuscoModel.FK__Adopcion__usuari__1920BF5C", "UsuarioAlbergue").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioAlbergue>("BD_EraCuscoModel.FK__Adopcion__usuari__1920BF5C", "UsuarioAlbergue").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UsuarioAlbergue> UsuarioAlbergue1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioAlbergue>("BD_EraCuscoModel.FK__Adopcion__usuari__1920BF5C", "UsuarioAlbergue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UsuarioAlbergue>("BD_EraCuscoModel.FK__Adopcion__usuari__1920BF5C", "UsuarioAlbergue", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_EraCuscoModel", Name="Mascota")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Mascota : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Mascota.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static Mascota CreateMascota(global::System.Int32 id)
        {
            Mascota mascota = new Mascota();
            mascota.id = id;
            return mascota;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true, "nombre");
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true, "descripcion");
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> etapaVida
        {
            get
            {
                return _etapaVida;
            }
            set
            {
                OnetapaVidaChanging(value);
                ReportPropertyChanging("etapaVida");
                _etapaVida = StructuralObject.SetValidValue(value, "etapaVida");
                ReportPropertyChanged("etapaVida");
                OnetapaVidaChanged();
            }
        }
        private Nullable<global::System.Int32> _etapaVida;
        partial void OnetapaVidaChanging(Nullable<global::System.Int32> value);
        partial void OnetapaVidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechaRegistro
        {
            get
            {
                return _fechaRegistro;
            }
            set
            {
                OnfechaRegistroChanging(value);
                ReportPropertyChanging("fechaRegistro");
                _fechaRegistro = StructuralObject.SetValidValue(value, "fechaRegistro");
                ReportPropertyChanged("fechaRegistro");
                OnfechaRegistroChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechaRegistro;
        partial void OnfechaRegistroChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaRegistroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value, true, "tipo");
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String raza
        {
            get
            {
                return _raza;
            }
            set
            {
                OnrazaChanging(value);
                ReportPropertyChanging("raza");
                _raza = StructuralObject.SetValidValue(value, true, "raza");
                ReportPropertyChanged("raza");
                OnrazaChanged();
            }
        }
        private global::System.String _raza;
        partial void OnrazaChanging(global::System.String value);
        partial void OnrazaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, "estado");
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private Nullable<global::System.Int32> _estado;
        partial void OnestadoChanging(Nullable<global::System.Int32> value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rutaFoto
        {
            get
            {
                return _rutaFoto;
            }
            set
            {
                OnrutaFotoChanging(value);
                ReportPropertyChanging("rutaFoto");
                _rutaFoto = StructuralObject.SetValidValue(value, true, "rutaFoto");
                ReportPropertyChanged("rutaFoto");
                OnrutaFotoChanged();
            }
        }
        private global::System.String _rutaFoto;
        partial void OnrutaFotoChanging(global::System.String value);
        partial void OnrutaFotoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> usuarioAlbergue
        {
            get
            {
                return _usuarioAlbergue;
            }
            set
            {
                OnusuarioAlbergueChanging(value);
                ReportPropertyChanging("usuarioAlbergue");
                _usuarioAlbergue = StructuralObject.SetValidValue(value, "usuarioAlbergue");
                ReportPropertyChanged("usuarioAlbergue");
                OnusuarioAlbergueChanged();
            }
        }
        private Nullable<global::System.Int32> _usuarioAlbergue;
        partial void OnusuarioAlbergueChanging(Nullable<global::System.Int32> value);
        partial void OnusuarioAlbergueChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_EraCuscoModel", "FK__Adopcion__mascot__182C9B23", "Adopcion")]
        public EntityCollection<Adopcion> Adopcion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Adopcion>("BD_EraCuscoModel.FK__Adopcion__mascot__182C9B23", "Adopcion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Adopcion>("BD_EraCuscoModel.FK__Adopcion__mascot__182C9B23", "Adopcion", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_EraCuscoModel", "FK__Mascota__usuario__1DE57479", "UsuarioAlbergue")]
        public UsuarioAlbergue UsuarioAlbergue1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioAlbergue>("BD_EraCuscoModel.FK__Mascota__usuario__1DE57479", "UsuarioAlbergue").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioAlbergue>("BD_EraCuscoModel.FK__Mascota__usuario__1DE57479", "UsuarioAlbergue").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UsuarioAlbergue> UsuarioAlbergue1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioAlbergue>("BD_EraCuscoModel.FK__Mascota__usuario__1DE57479", "UsuarioAlbergue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UsuarioAlbergue>("BD_EraCuscoModel.FK__Mascota__usuario__1DE57479", "UsuarioAlbergue", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_EraCuscoModel", "FK__Solicitud__masco__1BFD2C07", "Solicitud")]
        public EntityCollection<Solicitud> Solicitud
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Solicitud>("BD_EraCuscoModel.FK__Solicitud__masco__1BFD2C07", "Solicitud");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Solicitud>("BD_EraCuscoModel.FK__Solicitud__masco__1BFD2C07", "Solicitud", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_EraCuscoModel", Name="Solicitud")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Solicitud : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Solicitud.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static Solicitud CreateSolicitud(global::System.Int32 id)
        {
            Solicitud solicitud = new Solicitud();
            solicitud.id = id;
            return solicitud;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adNombre
        {
            get
            {
                return _adNombre;
            }
            set
            {
                OnadNombreChanging(value);
                ReportPropertyChanging("adNombre");
                _adNombre = StructuralObject.SetValidValue(value, true, "adNombre");
                ReportPropertyChanged("adNombre");
                OnadNombreChanged();
            }
        }
        private global::System.String _adNombre;
        partial void OnadNombreChanging(global::System.String value);
        partial void OnadNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adPaterno
        {
            get
            {
                return _adPaterno;
            }
            set
            {
                OnadPaternoChanging(value);
                ReportPropertyChanging("adPaterno");
                _adPaterno = StructuralObject.SetValidValue(value, true, "adPaterno");
                ReportPropertyChanged("adPaterno");
                OnadPaternoChanged();
            }
        }
        private global::System.String _adPaterno;
        partial void OnadPaternoChanging(global::System.String value);
        partial void OnadPaternoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adMaterno
        {
            get
            {
                return _adMaterno;
            }
            set
            {
                OnadMaternoChanging(value);
                ReportPropertyChanging("adMaterno");
                _adMaterno = StructuralObject.SetValidValue(value, true, "adMaterno");
                ReportPropertyChanged("adMaterno");
                OnadMaternoChanged();
            }
        }
        private global::System.String _adMaterno;
        partial void OnadMaternoChanging(global::System.String value);
        partial void OnadMaternoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adDni
        {
            get
            {
                return _adDni;
            }
            set
            {
                OnadDniChanging(value);
                ReportPropertyChanging("adDni");
                _adDni = StructuralObject.SetValidValue(value, true, "adDni");
                ReportPropertyChanged("adDni");
                OnadDniChanged();
            }
        }
        private global::System.String _adDni;
        partial void OnadDniChanging(global::System.String value);
        partial void OnadDniChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adDireccion
        {
            get
            {
                return _adDireccion;
            }
            set
            {
                OnadDireccionChanging(value);
                ReportPropertyChanging("adDireccion");
                _adDireccion = StructuralObject.SetValidValue(value, true, "adDireccion");
                ReportPropertyChanged("adDireccion");
                OnadDireccionChanged();
            }
        }
        private global::System.String _adDireccion;
        partial void OnadDireccionChanging(global::System.String value);
        partial void OnadDireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tipoVivienda
        {
            get
            {
                return _tipoVivienda;
            }
            set
            {
                OntipoViviendaChanging(value);
                ReportPropertyChanging("tipoVivienda");
                _tipoVivienda = StructuralObject.SetValidValue(value, true, "tipoVivienda");
                ReportPropertyChanged("tipoVivienda");
                OntipoViviendaChanged();
            }
        }
        private global::System.String _tipoVivienda;
        partial void OntipoViviendaChanging(global::System.String value);
        partial void OntipoViviendaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> otrasMascotas
        {
            get
            {
                return _otrasMascotas;
            }
            set
            {
                OnotrasMascotasChanging(value);
                ReportPropertyChanging("otrasMascotas");
                _otrasMascotas = StructuralObject.SetValidValue(value, "otrasMascotas");
                ReportPropertyChanged("otrasMascotas");
                OnotrasMascotasChanged();
            }
        }
        private Nullable<global::System.Int32> _otrasMascotas;
        partial void OnotrasMascotasChanging(Nullable<global::System.Int32> value);
        partial void OnotrasMascotasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechaEmision
        {
            get
            {
                return _fechaEmision;
            }
            set
            {
                OnfechaEmisionChanging(value);
                ReportPropertyChanging("fechaEmision");
                _fechaEmision = StructuralObject.SetValidValue(value, "fechaEmision");
                ReportPropertyChanged("fechaEmision");
                OnfechaEmisionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechaEmision;
        partial void OnfechaEmisionChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaEmisionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, "estado");
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private Nullable<global::System.Int32> _estado;
        partial void OnestadoChanging(Nullable<global::System.Int32> value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> mascota
        {
            get
            {
                return _mascota;
            }
            set
            {
                OnmascotaChanging(value);
                ReportPropertyChanging("mascota");
                _mascota = StructuralObject.SetValidValue(value, "mascota");
                ReportPropertyChanged("mascota");
                OnmascotaChanged();
            }
        }
        private Nullable<global::System.Int32> _mascota;
        partial void OnmascotaChanging(Nullable<global::System.Int32> value);
        partial void OnmascotaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> adoptante
        {
            get
            {
                return _adoptante;
            }
            set
            {
                OnadoptanteChanging(value);
                ReportPropertyChanging("adoptante");
                _adoptante = StructuralObject.SetValidValue(value, "adoptante");
                ReportPropertyChanged("adoptante");
                OnadoptanteChanged();
            }
        }
        private Nullable<global::System.Int32> _adoptante;
        partial void OnadoptanteChanging(Nullable<global::System.Int32> value);
        partial void OnadoptanteChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_EraCuscoModel", "FK__Adopcion__solici__1B0907CE", "Adopcion")]
        public EntityCollection<Adopcion> Adopcion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Adopcion>("BD_EraCuscoModel.FK__Adopcion__solici__1B0907CE", "Adopcion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Adopcion>("BD_EraCuscoModel.FK__Adopcion__solici__1B0907CE", "Adopcion", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_EraCuscoModel", "FK__Solicitud__masco__1BFD2C07", "Mascota")]
        public Mascota Mascota1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mascota>("BD_EraCuscoModel.FK__Solicitud__masco__1BFD2C07", "Mascota").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mascota>("BD_EraCuscoModel.FK__Solicitud__masco__1BFD2C07", "Mascota").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Mascota> Mascota1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mascota>("BD_EraCuscoModel.FK__Solicitud__masco__1BFD2C07", "Mascota");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Mascota>("BD_EraCuscoModel.FK__Solicitud__masco__1BFD2C07", "Mascota", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_EraCuscoModel", "FK__Solicitud__adopt__1CF15040", "UsuarioAdoptante")]
        public UsuarioAdoptante UsuarioAdoptante
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioAdoptante>("BD_EraCuscoModel.FK__Solicitud__adopt__1CF15040", "UsuarioAdoptante").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioAdoptante>("BD_EraCuscoModel.FK__Solicitud__adopt__1CF15040", "UsuarioAdoptante").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UsuarioAdoptante> UsuarioAdoptanteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioAdoptante>("BD_EraCuscoModel.FK__Solicitud__adopt__1CF15040", "UsuarioAdoptante");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UsuarioAdoptante>("BD_EraCuscoModel.FK__Solicitud__adopt__1CF15040", "UsuarioAdoptante", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_EraCuscoModel", Name="UsuarioAdoptante")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UsuarioAdoptante : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto UsuarioAdoptante.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static UsuarioAdoptante CreateUsuarioAdoptante(global::System.Int32 id)
        {
            UsuarioAdoptante usuarioAdoptante = new UsuarioAdoptante();
            usuarioAdoptante.id = id;
            return usuarioAdoptante;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true, "nombre");
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aPaterno
        {
            get
            {
                return _aPaterno;
            }
            set
            {
                OnaPaternoChanging(value);
                ReportPropertyChanging("aPaterno");
                _aPaterno = StructuralObject.SetValidValue(value, true, "aPaterno");
                ReportPropertyChanged("aPaterno");
                OnaPaternoChanged();
            }
        }
        private global::System.String _aPaterno;
        partial void OnaPaternoChanging(global::System.String value);
        partial void OnaPaternoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aMaterno
        {
            get
            {
                return _aMaterno;
            }
            set
            {
                OnaMaternoChanging(value);
                ReportPropertyChanging("aMaterno");
                _aMaterno = StructuralObject.SetValidValue(value, true, "aMaterno");
                ReportPropertyChanged("aMaterno");
                OnaMaternoChanged();
            }
        }
        private global::System.String _aMaterno;
        partial void OnaMaternoChanging(global::System.String value);
        partial void OnaMaternoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dni
        {
            get
            {
                return _dni;
            }
            set
            {
                OndniChanging(value);
                ReportPropertyChanging("dni");
                _dni = StructuralObject.SetValidValue(value, true, "dni");
                ReportPropertyChanged("dni");
                OndniChanged();
            }
        }
        private global::System.String _dni;
        partial void OndniChanging(global::System.String value);
        partial void OndniChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value, true, "telefono");
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private global::System.String _telefono;
        partial void OntelefonoChanging(global::System.String value);
        partial void OntelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String correo
        {
            get
            {
                return _correo;
            }
            set
            {
                OncorreoChanging(value);
                ReportPropertyChanging("correo");
                _correo = StructuralObject.SetValidValue(value, true, "correo");
                ReportPropertyChanged("correo");
                OncorreoChanged();
            }
        }
        private global::System.String _correo;
        partial void OncorreoChanging(global::System.String value);
        partial void OncorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dirección
        {
            get
            {
                return _dirección;
            }
            set
            {
                OndirecciónChanging(value);
                ReportPropertyChanging("dirección");
                _dirección = StructuralObject.SetValidValue(value, true, "dirección");
                ReportPropertyChanged("dirección");
                OndirecciónChanged();
            }
        }
        private global::System.String _dirección;
        partial void OndirecciónChanging(global::System.String value);
        partial void OndirecciónChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String clave
        {
            get
            {
                return _clave;
            }
            set
            {
                OnclaveChanging(value);
                ReportPropertyChanging("clave");
                _clave = StructuralObject.SetValidValue(value, true, "clave");
                ReportPropertyChanged("clave");
                OnclaveChanged();
            }
        }
        private global::System.String _clave;
        partial void OnclaveChanging(global::System.String value);
        partial void OnclaveChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_EraCuscoModel", "FK__Adopcion__adopta__1A14E395", "Adopcion")]
        public EntityCollection<Adopcion> Adopcion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Adopcion>("BD_EraCuscoModel.FK__Adopcion__adopta__1A14E395", "Adopcion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Adopcion>("BD_EraCuscoModel.FK__Adopcion__adopta__1A14E395", "Adopcion", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_EraCuscoModel", "FK__Solicitud__adopt__1CF15040", "Solicitud")]
        public EntityCollection<Solicitud> Solicitud
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Solicitud>("BD_EraCuscoModel.FK__Solicitud__adopt__1CF15040", "Solicitud");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Solicitud>("BD_EraCuscoModel.FK__Solicitud__adopt__1CF15040", "Solicitud", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_EraCuscoModel", Name="UsuarioAlbergue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UsuarioAlbergue : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto UsuarioAlbergue.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static UsuarioAlbergue CreateUsuarioAlbergue(global::System.Int32 id)
        {
            UsuarioAlbergue usuarioAlbergue = new UsuarioAlbergue();
            usuarioAlbergue.id = id;
            return usuarioAlbergue;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true, "nombre");
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aPaterno
        {
            get
            {
                return _aPaterno;
            }
            set
            {
                OnaPaternoChanging(value);
                ReportPropertyChanging("aPaterno");
                _aPaterno = StructuralObject.SetValidValue(value, true, "aPaterno");
                ReportPropertyChanged("aPaterno");
                OnaPaternoChanged();
            }
        }
        private global::System.String _aPaterno;
        partial void OnaPaternoChanging(global::System.String value);
        partial void OnaPaternoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aMaterno
        {
            get
            {
                return _aMaterno;
            }
            set
            {
                OnaMaternoChanging(value);
                ReportPropertyChanging("aMaterno");
                _aMaterno = StructuralObject.SetValidValue(value, true, "aMaterno");
                ReportPropertyChanged("aMaterno");
                OnaMaternoChanged();
            }
        }
        private global::System.String _aMaterno;
        partial void OnaMaternoChanging(global::System.String value);
        partial void OnaMaternoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dni
        {
            get
            {
                return _dni;
            }
            set
            {
                OndniChanging(value);
                ReportPropertyChanging("dni");
                _dni = StructuralObject.SetValidValue(value, true, "dni");
                ReportPropertyChanged("dni");
                OndniChanged();
            }
        }
        private global::System.String _dni;
        partial void OndniChanging(global::System.String value);
        partial void OndniChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value, true, "telefono");
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private global::System.String _telefono;
        partial void OntelefonoChanging(global::System.String value);
        partial void OntelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String correo
        {
            get
            {
                return _correo;
            }
            set
            {
                OncorreoChanging(value);
                ReportPropertyChanging("correo");
                _correo = StructuralObject.SetValidValue(value, true, "correo");
                ReportPropertyChanged("correo");
                OncorreoChanged();
            }
        }
        private global::System.String _correo;
        partial void OncorreoChanging(global::System.String value);
        partial void OncorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dirección
        {
            get
            {
                return _dirección;
            }
            set
            {
                OndirecciónChanging(value);
                ReportPropertyChanging("dirección");
                _dirección = StructuralObject.SetValidValue(value, true, "dirección");
                ReportPropertyChanged("dirección");
                OndirecciónChanged();
            }
        }
        private global::System.String _dirección;
        partial void OndirecciónChanging(global::System.String value);
        partial void OndirecciónChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> rango
        {
            get
            {
                return _rango;
            }
            set
            {
                OnrangoChanging(value);
                ReportPropertyChanging("rango");
                _rango = StructuralObject.SetValidValue(value, "rango");
                ReportPropertyChanged("rango");
                OnrangoChanged();
            }
        }
        private Nullable<global::System.Int32> _rango;
        partial void OnrangoChanging(Nullable<global::System.Int32> value);
        partial void OnrangoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String clave
        {
            get
            {
                return _clave;
            }
            set
            {
                OnclaveChanging(value);
                ReportPropertyChanging("clave");
                _clave = StructuralObject.SetValidValue(value, true, "clave");
                ReportPropertyChanged("clave");
                OnclaveChanged();
            }
        }
        private global::System.String _clave;
        partial void OnclaveChanging(global::System.String value);
        partial void OnclaveChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_EraCuscoModel", "FK__Adopcion__usuari__1920BF5C", "Adopcion")]
        public EntityCollection<Adopcion> Adopcion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Adopcion>("BD_EraCuscoModel.FK__Adopcion__usuari__1920BF5C", "Adopcion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Adopcion>("BD_EraCuscoModel.FK__Adopcion__usuari__1920BF5C", "Adopcion", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_EraCuscoModel", "FK__Mascota__usuario__1DE57479", "Mascota")]
        public EntityCollection<Mascota> Mascota
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Mascota>("BD_EraCuscoModel.FK__Mascota__usuario__1DE57479", "Mascota");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Mascota>("BD_EraCuscoModel.FK__Mascota__usuario__1DE57479", "Mascota", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
