//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EraCuscoWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adopcion
    {
        public int id { get; set; }
        public string adNombre { get; set; }
        public string adPaterno { get; set; }
        public string adMaterno { get; set; }
        public string adDni { get; set; }
        public string adDireccion { get; set; }
        public string tipoVivienda { get; set; }
        public Nullable<int> otrasMascotas { get; set; }
        public Nullable<int> esteriziacion { get; set; }
        public Nullable<System.DateTime> fechaEmision { get; set; }
        public Nullable<int> mascota { get; set; }
        public Nullable<int> usuarioAlbergue { get; set; }
        public Nullable<int> adoptante { get; set; }
        public Nullable<int> solicitud { get; set; }
    
        public virtual UsuarioAdoptante UsuarioAdoptante { get; set; }
        public virtual Mascota Mascota1 { get; set; }
        public virtual Solicitud Solicitud1 { get; set; }
        public virtual UsuarioAlbergue UsuarioAlbergue1 { get; set; }
    }
}
