//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EraCuscoWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud()
        {
            this.Adopcion = new HashSet<Adopcion>();
        }
    
        public int id { get; set; }
        public string adNombre { get; set; }
        public string adPaterno { get; set; }
        public string adMaterno { get; set; }
        public string adDni { get; set; }
        public string adDireccion { get; set; }
        public string tipoVivienda { get; set; }
        public Nullable<int> otrasMascotas { get; set; }
        public Nullable<System.DateTime> fechaEmision { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> mascota { get; set; }
        public Nullable<int> adoptante { get; set; }
        public string adTelefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adopcion> Adopcion { get; set; }
        public virtual Mascota Mascota1 { get; set; }
        public virtual UsuarioAdoptante UsuarioAdoptante { get; set; }
    }
}
